# Generated by Django 5.0.4 on 2024-04-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meals_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='slug',
        ),
    ]
