# Generated by Django 5.0.4 on 2024-04-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_meals_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'meal', 'verbose_name_plural': 'meals'},
        ),
    ]
